---
- name: Add entry to prometheus.yml
  ansible.builtin.lineinfile:
    path: /opt/prometheus/prometheus.yml
    insertafter: '      - targets: \[''localhost:9100''\]'
    regexp: '      - targets: \[''{{ hostvar }}:{{ prom_port }}''\]'
    line: "      - targets: ['{{ hostvar }}:{{ prom_port }}']"
  when: hostvar is defined 
  notify: Restart prometheus container

- name: Add entry(s) to prometheus.yml (from project)
  ansible.builtin.lineinfile:
    path: /opt/prometheus/prometheus.yml
    insertafter: '      - targets: \[''localhost:9100''\]'
    regexp: '      - targets: \[''{{ prom_line_item }}.{{ dns_suffix_list[0] }}:{{ prom_port }}''\]'
    line: "      - targets: ['{{ prom_line_item }}.{{ dns_suffix_list[0] }}:{{ prom_port }}']"
  loop: "{{ vm_name_list }}"
  loop_control:
    loop_var: prom_line_item
  when: vm_name_list is defined
  notify: Restart prometheus container